format = """
[](fg:nord7)[ ](bg:nord7)\
$username\
$hostname\
[](fg:nord7 bg:nord9)\
$directory\
[](fg:nord9 bg:nord10)\
$git_branch\
$git_status\
$character"""

add_newline = false
palette = 'nord'

[palettes.nord]
nord0  = '#2E3440' # background (dark), text (light)
nord1  = '#3B4252' # selection (dark), 
nord2  = '#434C5E'
nord3  = '#4C566A'
nord4  = '#D8DEE9'
nord5  = '#E5E9F0'
nord6  = '#ECEFF4'
nord7  = '#8FBCBB'
nord8  = '#88C0D0'
nord9  = '#81A1C1'
nord10 = '#5E81AC'
nord11 = '#BF616A'
nord12 = '#D08770'
nord13 = '#EBCB8B'
nord14 = '#A3BE8C'
nord15 = '#B48EAD'


[character]
success_symbol = '[](nord10)'
error_symbol = '[](nord11)'

[username]
show_always = false
style_user = "fg:nord0 bg:nord7"
style_root = "fg:nord0 bg:nord7"
format = '[$user@]($style)'
disabled = false

[hostname]
ssh_only = false
style = "fg:nord0 bg:nord7"
format = '[$hostname ]($style)'
aliases = { "head" = "" }
disabled = false

[directory]
style = "fg:nord0 bg:nord9"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = ""
style = "bg:nord10"
format = '[[ $symbol $branch ](fg:nord0 bg:nord10)]($style)'
truncation_length = 8
truncation_symbol = '…'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:nord0 bg:nord10)]($style)'
